### ISSUE TITLE
support vscode 1.96.1

### ISSUE THREAD

**Issue by Hazi7** [flexpilot-ai/vscode-extension#12]
support vscode 1.96.1

**Comment by mohankumarelec** [comment]
Hi @Hazi7,

Thank you for actively using our extension!

With the release of VS Code 1.96.1, GitHub Copilot-related marketing messages have been integrated into the editor itself. To hide the default Copilot pop-up in older versions, you can manually run the `Chat: Hide Copilot` command.

Good news! The latest version of Flexpilot (v1.96.1) now automates this for you. Upon startup, it automatically triggers the hide command, ensuring a seamless experience.

You can check out the release here: [Flexpilot v1.96.1](https://github.com/flexpilot-ai/vscode-extension/releases/tag/1.96.1).

Happy coding!
