### ISSUE TITLE
Flexpilot Extension Not Compatible with VS Code Insiders V1.96.0-insider

### ISSUE THREAD

**Issue by shadyar-bakr** [flexpilot-ai/vscode-extension#8]
The Flexpilot VS Code extension is currently incompatible with VS Code Insiders. When installed in the Insiders build:
```
Can't install 'flexpilot.flexpilot-vscode-extension' extension 
because it is not compatible with the current version of
Visual Studio Code - Insiders (version 1.96.0-insider).
```

**Comment by mohankumarelec** [comment]
Hi @shadyar-bakr,

Thank you for reaching out! Currently, our extension supports only the stable version of VS Code. Support for the Insiders build is on our backlog, and we plan to include it in a future update.

We appreciate your understanding and patience!
